start this project. When using Map it happened unknown issue: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/c++/4.2.1/bits/stl_function.h:227: error: invalid operands to binary expression ('const Vector<std::basic_string<char> >' and 'const Vector<std::basic_string<char> >')       { return __x < __y; } 	                 ~~~ ^ ~~~
If I changed to use HashMap,it became:
:-1: error: [Ngrams.app/Contents/MacOS/Ngrams] Error 1

Just don't know how to solve it.
Tomorrow may try it on PC